DOT/DOT/Controllers/GradesController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using DOT.Security;
using DOT.Services.Services;
using DOT.ViewModels;

namespace DOT.Controllers
{
    [AuthorizeIsConnectedToPjatk]
    public class GradesController : Controller
    {
        private readonly GradesService _gradesService;

        public GradesController()
        {
            _gradesService = new GradesService();
        }

        public async Task<ActionResult> Index()
        {
            var data = await _gradesService.GetGrades();

            var grades = data
                .GroupBy(x => x.Semester)
                .Select(group => new GradesViewModel
                {
                    Name = group.Key,
                    Grades = group.ToList()
                }).ToList();
            
            return View(grades);
        }
    }
}

DOT/DOT/Controllers/LanguageController.cs
using System.Web;
using System.Web.Mvc;
using DOT.Utils;

namespace DOT.Controllers
{
    [AllowAnonymous]
    public class LanguageController : Controller
    {
        public ActionResult English()
        {
            Response.Cookies.Add(new HttpCookie(Localizations.LanguageCookieName, Localizations.EnglishCultureCode));

            if (Request.UrlReferrer != null)
            {
                return Redirect(Request.UrlReferrer.AbsoluteUri);
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Polish()
        {
            Response.Cookies.Add(new HttpCookie(Localizations.LanguageCookieName, Localizations.PolishCultureCode));

            if (Request.UrlReferrer != null)
            {
                return Redirect(Request.UrlReferrer.AbsoluteUri);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

DOT/DOT/Controllers/PaymentsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using DOT.Security;
using DOT.Services.Services;
using DOT.ViewModels;

namespace DOT.Controllers
{
    [AuthorizeIsConnectedToPjatk]
    public class PaymentsController : Controller
    {
        private readonly PaymentsService _paymentsService;
        private readonly StudentService _studentService;

        public PaymentsController()
        {
            _paymentsService = new PaymentsService();
            _studentService = new StudentService();
        }

        public async Task<ActionResult> Index()
        {
            return View(new PaymentsViewModel
            {
                Payments = await _paymentsService.GetPayments(),
                Fees = await _paymentsService.GetFees(),
                StudentInfo = await _studentService.GetStudentInfo()
            });
        }
    }
}

DOT/DOT/Controllers/ScheduleController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using DOT.Security;
using DOT.Services.Services;
using DOT.ViewModels;

namespace DOT.Controllers
{
    [AuthorizeIsConnectedToPjatk]
    public class ScheduleController : Controller
    {
        private readonly ScheduleService _scheduleService;

        public ScheduleController()
        {
            _scheduleService = new ScheduleService();
        }

        public async Task<ActionResult> Index()
        {
            var today = DateTime.Today;
            var data = await _scheduleService.GetSchedules(today, today.AddYears(1));

            var schedules = data
                .GroupBy(x => x.StartDate.Date)
                .Select(group => new ScheduleViewModel
                {
                    Date = group.Key,
                    Schedules = group.ToList()
                }).ToList();

            return View(schedules);
        }
    }
}

DOT/DOT/Views/Shared/_Layout.cshtml
@using DOT.Domain.Utils
@using DOT.Resources
@using DOT.Security
@using DOT.Utils
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PJATK Viewer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type='text/javascript'>
        var appInsights = window.appInsights || function (config) {
            // ReSharper disable once JoinDeclarationAndInitializerJs
            var t;
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } }

            t = { config: config };
            var u = document, e = window, o = 'script', s = u.createElement(o), i, f; for (s.src = config.url || '//az416426.vo.msecnd.net/scripts/a/ai.0.js', u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ['Event', 'Exception', 'Metric', 'PageView', 'Trace', 'Ajax']; i.length;)r('track' + i.pop()); return r('setAuthenticatedUserContext'), r('clearAuthenticatedUserContext'), config.disableExceptionTracking || (i = 'onerror', r('_' + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== true && t['_' + i](config, r, u, e, o), s }), t;
        }({
            instrumentationKey: '95dc91e9-5f4b-4c09-ad3d-001d77e2617d'
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PJATK", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (HttpContext.Current.GetOwinContext().Authentication.User.IsConnectedToPjatk())
                    {
                        <li>@Html.ActionLink(Global.Grades, "Index", "Grades")</li>
                        <li>@Html.ActionLink(Global.Schedule, "Index", "Schedule")</li>
                        <li>@Html.ActionLink(Global.Payments, "Index", "Payments")</li>
                    }
                    <li>
                        @(Localizations.IsUserLanguageEnglish(Request) 
                            ? Html.ActionLink("Polski", "Polish", "Language", null, new {@class = "language-switcher polish", id = "languageSwitcher"}) 
                            : Html.ActionLink("English", "English", "Language", null, new {@class = "language-switcher english", id = "languageSwitcher"}))
                    </li>
                    @if (HttpContext.Current.GetOwinContext().Authentication.User.HasPermission(Permission.AdminSectionDisplay.GetDescription()))
                    {
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                Admin<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink(Global.Users, "Users", "Admin")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dawid Richert</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <!-- JS Resources - this partial contains a JS module that contains resources
    and it has to be included before the rest because values form it are used in other scripts -->
    @Html.Partial("~/Views/JSResources/Index.cshtml")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
</body>
</html>