DOT/DOT/Controllers/ConnectController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using DOT.Resources;
using DOT.Security;
using DOT.Services.Services;
using DOT.Utils;
using DOT.ViewModels;

namespace DOT.Controllers
{
    public class ConnectController : Controller
    {
        private readonly DotUserService _dotUserService;

        public ConnectController()
        {
            _dotUserService = new DotUserService();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(ConnectAccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _dotUserService.ConnectAccount(model.Login, model.Password);
                if (result)
                {
                    User.AddUpdateClaim(ClaimsPrincipalExtensions.DotIsConnectedToPjatkClaimName, true.ToString());
                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError("", Global.InvalidCredentials);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Disconnect()
        {
            if (ModelState.IsValid)
            {
                var result = await _dotUserService.DisconnectAccount();
                if (result)
                {
                    User.AddUpdateClaim(ClaimsPrincipalExtensions.DotIsConnectedToPjatkClaimName, false.ToString());
                }
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

DOT/DOT/Views/Connect/Index.cshtml
@using DOT.Resources
@model DOT.ViewModels.ConnectAccountViewModel
@{
    ViewBag.Title = Global.ConnectToPjatk;
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Index", "Connect", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>@Global.ConnectToPjatkMessage</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Login, new { @class = "col-md-2 control-label" })
        <div class="col-md-3 input-group">
            @Html.TextBoxFor(m => m.Login, new { @class = "form-control" })
            <span class="input-group-addon">@@pjwstk.edu.pl</span>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="@Global.Connect" />
        </div>
    </div>
}